version: "3.7"
services:
  web-server:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - "../:/var/www/html"
    ports:
      - "8080:80"
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
    expose:
      - 9003
  mysql-server:
    image: mysql:8.0.27
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mysql-data:
